name: Trigger GitBook to Fluid Topics Converter

on:
#  push:
#    branches:
#      - main  # Adjust to target specific branches
  workflow_dispatch:
    inputs:
      COMMIT_HASH:
        description: 'Optional commit hash to process'
        required: false


jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger private repo action
        uses: jfrog/Gitbook-to-FT/.github/actions/analyze-code@main
        with:
          repo_url: ${{ github.repository }}
          branch: ${{ github.ref_name }}
        env:
          FLUID_TOPICS_API_KEY: ${{ secrets.FLUID_TOPICS_API_KEY }}
          FLUID_TOPICS_BASE_URL: ${{ secrets.FLUID_TOPICS_BASE_URL }}
          FLUID_TOPICS_SOURCE_ID: ${{ secrets.FLUID_TOPICS_SOURCE_ID }}
          PUBLICATION_TITLE: ${{ secrets.PUBLICATION_TITLE }}
