name: Migrate Documentation to Fluid Topics

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      COMMIT_HASH:
        description: 'Optional commit hash to process'
        required: false

jobs:
  migrate-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Clone Gitbook content
        run: |
          mkdir -p gitbook-content
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git gitbook-content
          cd gitbook-content
          git checkout ${{ inputs.COMMIT_HASH || github.sha }}
      
      # Step 2: Clone Gitbook to FT
      - name: Clone Gitbook to FT Utility
        run: |
          git clone https://github.com/jfrog/Gitbook-to-FT.git

      - name: ls -l
        run: |
          ls -l

     # Step 4: Set up Python and install dependencies
      - name: Install Python and required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -r Gitbook-to-FT/requirements.txt

      # Step 6: Run migration utility
      - name: Run migration utility
        env:
          GITBOOK_REPO_FOLDER: "gitbook-content"
          FLUID_TOPICS_API_KEY: ${{ secrets.FLUID_TOPICS_API_KEY }}
          FLUID_TOPICS_BASE_URL: ${{ vars.FLUID_TOPICS_BASE_URL }}
          FLUID_TOPICS_SOURCE_ID: ${{ vars.FLUID_TOPICS_SOURCE_ID }}
          PUBLICATION_TITLE: ${{ vars.PUBLICATION_TITLE }}
        run: |
          python Gitbook-to-FT/main.py
